# Generated by Django 3.0.5 on 2020-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='bio',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
